spring.application.name=engine

spring.thymeleaf.cache=true
server.error.whitelabel.enabled=false

spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile

metadefender.api.key=
uploadcare.api.key=
